[package]
name = "3dtile"
version = "0.1.0"
authors = ["fanzhenhua <fanzhenhua@superengine.com.cn>"]

[dependencies]
libc = "0.2"
clap = "2.0"
rayon = "1.0.0"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[build-dependencies]
cc = "1.0.*"